### ISSUE TITLE
Segfault/stack smash on loooong DB2 error messages?

### ISSUE THREAD

**Issue by RocketRooster** [w1nk/node-odbc#57] opened 2014-02-25 12:52 UTC
Hi there Dan,

Thanks for the great work on node-odbc!

Anyway, I have a peculiar problem. I am able to connect to DB2 successfully, and insert data and run queries without any problems (normally). However, the other day while testing one of my input screens, I deliberately performed a duplicate insert on a table (i.e UNIQUE key constraint violation).

Node immediately segfaults with the ol' **_stack smashing detected**_ error message upon performing an ODBCStatement.execute(). I can very reliably duplicate this error time and again. Other error messages are returned as expected and I can handle them. But not this one.

I have a sneaky suspicion (if you'll forgive the potential red herring) that it is to do with the extreme length of the DB2 error message (It's over 300 characters):

SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "3" constrains "TEST.COMPANY" from having duplicate values for the index key.  SQLSTATE=23505

(this was copied from the db2 CLP after executing the same statement that creates the segfault in node)

I have tried testing this theory by creating a BEFORE INSERT trigger on a test table which throws a custom error but, alas, DB2 user error messages are limited to 70 characters, and so the error "succeeds" (i.e. no segfault).

I have no idea whether this problem lies with node, node-odbc or with unixODBC.

For now, I am working around the problem using a stored procedure to do my deletes, but it is a pain. And it makes be worry about other potential issues waiting to harass :)

System specs:

Ubuntu 12.0.4 64-bit
DB2 Express-C V10.5 64-bit, and using the 64-bit db2lib.so client library.
unixODBC 2.3.2 (compiled for 64-bit)
node-odbc 0.6.2
nodejs 0.10.23

Any pointers or suggestions would be greatly appreciated!

Many thanks and warm regards,
Riaan

P.S If any further info (test case source, etc) is required to help solve this, please shout.

**Comment by wankdanker** [comment] 2014-02-25 16:48
Hi Riaan,

Thank you for the detailed report. You may be right and it might have to do with the length of the error message. The buffer for the error message is 512 bytes. It would seem to be enough room for a 300 character error message, but if UNICODE is enabled, then that might actually be ~600 bytes. There are two things you can try to confirm if this is the case:
- Disable UNICODE
  - See: https://github.com/wankdanker/node-odbc#unicode
- Increase the buffer size and rebuild
  - https://github.com/wankdanker/node-odbc/blob/master/src/odbc.cpp#L800
  - Edit src/odbc.ccp; on line 814, increase 512 to some larger number; maybe 1024

It's also possible that this is not the case. Because we do pass the length of the buffer to the function that returns the error message. I am interested to hear the results of either of these tests.

Good luck,

Dan

**Comment by RocketRooster** [comment] 2014-02-26 05:44
Hi Dan,

Both suggestions solve the issue:

1) Disabling Unicode and keeping the buffer size at 512;
2) Increasing the buffer size to 1024 and re-enabling Unicode (I have left it in this state for now)

I haven't had a further dig but it would then appear as if SQLGetDiagRec is being sanguine about the sizes passed to it.

Thanks for the help!
Riaan

**Comment by wankdanker** [comment] 2014-02-27 22:43
Hi Riaan,

I think I know what the problem is. Microsoft defines **BufferLength**, the argument to **SQLGetDiagRec** as:

> [Input] Length of the *MessageText buffer in characters. There is no maximum length of the diagnostic message text.

I am passing the size of the buffer in bytes and it should be characters. So, for UNICODE, it would generally be the number of bytes divided by two since there are two bytes per character. I'll get that fixed and push out v0.6.3.

Thanks,

Dan

**Comment by RocketRooster** [comment] 2014-02-28 04:49
Thank you for your hard work, Dan!

**Comment by wankdanker** [comment] 2014-05-23 16:35
Closing this issue. That's for helping out.

**Closed as completed by wankdanker** 2014-05-23 16:35 UTC
