### ISSUE TITLE
ODBC::GetColumnValue> (len == SQL_NULL_DATA) comparison always fails

### ISSUE THREAD

**Issue by RocketRooster** [w1nk/node-odbc#63] opened 2014-05-19 12:02 UTC
Hi Dan,

I have an issue where I was am getting spurious values for NULL columns. (DB2, Ubuntu 12.04 64 bit).

I have enabled debug, dug around a bit and have discovered that the (len == SQL_NULL_DATA) comparisons in this proc always fail. To wit:

```
case SQL_INTEGER :
case SQL_SMALLINT :
case SQL_TINYINT : {
    long value;

    ret = SQLGetData(
      hStmt,
      column.index,
      SQL_C_SLONG,
      &value,
      sizeof(value),
      &len);

    DEBUG_PRINTF("ODBC::GetColumnValue: SQL_NULL_DATA=%i\n",
                SQL_NULL_DATA);

    DEBUG_PRINTF("ODBC::GetColumnValue - Integer: index=%i name=%s type=%i len=%i ret=%i\n",
                column.index, column.name, column.type, len, ret);

    if (len == SQL_NULL_DATA) {
      DEBUG_PRINTF("len == SQL_NULL_DATA?:%i\n", len);
      return scope.Close(Null());
      //return Null();
    }
    else {
      DEBUG_PRINTF("len != SQL_NULL_DATA?:%i\n", len);
      return scope.Close(Integer::New(value));
      //return Integer::New(value);
    }
  }
  break;
```

You will note that I've added extra debug output lines to help me figure out what's what. I get the following debug output when traversing a null integer column (and any  null columns of other SQL types as well):

ODBC::GetColumnValue: SQL_NULL_DATA=-1
ODBC::GetColumnValue - Integer: index=2 name=S type=4 len=-1 ret=0
len != SQL_NULL_DATA?:-1

Clearly, -1 is not equal to -1 (!!!), so it's some sort of casting error. I am by no means an expert here so any pointers to help fix it the right way would be appreciated.

Thanks and regards,
Riaan

**Comment by RocketRooster** [comment] 2014-05-19 12:29
P.S, FWIW, unixODBC is compiled with -BUILD_LEGACY_64_BIT_MODE.

(odbc_config --ulen: -DSIZEOF_SQLULEN=8)

**Comment by wankdanker** [comment] 2014-05-19 12:37
Wow, that's a weird one. Just to double check, are you positive that node, unixodbc AND the db2 driver are all 64 bit? I have seen weird things happen with a 32 bit odbc driver running with node and unixodbc 64 bit. Apparently that combination still actually worked... sometimes....

Other than that, I'll have to find a way to reproduce this because I don't see this behavior in any of my tests. Could you share a part of your SQL query and data that reproduces this problem?

**Comment by wankdanker** [comment] 2014-05-19 12:37
Oh, that's interesting regarding the -BUILD_LEGACY_64_BIT_MODE. Was this a custom compiled unixODBC? Or is that the way it comes with Ubuntu 12.04?

**Comment by RocketRooster** [comment] 2014-05-19 12:43
Woah - I'm putting the cart before the horse it seems:

sizeof(SQLLEN) = 8
sizeof(SQL_NULL_DATA)=4

Clearly a 32/64 mismatch issue, I will first make sure my unixODBC is properly built and that nodeodbc is actually using the version I'm building. I'll keep you updated. Sorry for the bother!

**Comment by RocketRooster** [comment] 2014-05-19 12:44
unixODBC builds in 32-bit mode by default unless you export CFLAGS="-BUILD_LEGACY_64_BIT_MODE"

**Comment by RocketRooster** [comment] 2014-05-19 13:27
Well, I'm talking shyte. By default it builds in 64-bit mode, 32-bit mode is enabled with the above switch.

Anyway, I've now tried it all different ways and I still get the same issue. Urgh. I know it's a problem on my system... but where/how!?

**Comment by wankdanker** [comment] 2014-05-19 14:13
Ugh, that sucks. I am out of ideas at the moment. If anything comes to me, I'll let you know. Let me know if you figure it out. 

Dan

**Comment by RocketRooster** [comment] 2014-05-20 05:56
Morning Dan,

I have tried forcing the issue by declaring SQLLEN MY_SQL_NULL_DATA = -1 at the beginning of odbc.cpp and replacing all occurrences of SQL_NULL_DATA, but it still fails the comparison. I also tried (len == -1), that doesn't work either.

I can confirm that sql.h from the unixodbc source is being used when building nodeodbc (ferinstance, I can change the value of SQL_NULL_DATA, and it reflects as expected during node runtime). 

I'm a bit stuck at the moment, my C++ isn't nearly what it should be, but I will try a few more things.

Thanks!
Riaan

**Comment by RocketRooster** [comment] 2014-05-20 09:29
Hi Dan,

Just thought I'd mention, (len < 0) ALSO fails...very weird compiler snafu going on here.

**Comment by RocketRooster** [comment] 2014-05-20 12:25
Hi Dan,

This works: ((int)len == SQL_NULL_DATA)

For some reason, len is not returned as a fully bit-set 2's complement 64-bit value, even though it is 8 bytes long. Only the least significant 32 bits are used. I found this out by shifting bits ant printf'ing with %ld:

len << 1 = 8589934590
len >> 1 = 2147483647

No idea what's going on under the hood with my compiler setup, but at least I can carry on working!

Cheers!
Riaan

**Comment by wankdanker** [comment] 2014-05-20 14:24
Are you positive you are not using the 32bit DB2 driver?

**Comment by RocketRooster** [comment] 2014-05-21 06:12
Hi Dan,

I double-checked just in case. All seems in order:

```
riaan@acs:~$ odbcinst -j
unixODBC 2.3.2
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
USER DATA SOURCES..: /etc/odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

riaan@acs:~$ cat /usr/local/etc/odbcinst.ini
[DB2]
Description=DB2 Driver
Driver=/opt/ibm/db2/V10.5/lib64/libdb2.so.1
Driver64=/opt/ibm/db2/V10.5/lib64/libdb2.so.1
FileUsage=1
DontDLClose=1

riaan@acs:~$ cat /usr/local/etc/odbc.ini
[ODBC]
Trace=Yes
Tracefile=/tmp/odbc.log
Pooling=no

riaan@acs:~$ file /opt/ibm/db2/V10.5/lib64/libdb2.so.1
/opt/ibm/db2/V10.5/lib64/libdb2.so.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x513c0fa7a0611881d9ae3423bd16b534adb1b4dc, not stripped
```

Regards,
Riaan

**Comment by RocketRooster** [comment] 2014-05-21 06:18
That said, I am specifying the driver in my ODBC connection string like so:

```
DBConn.openSync('DRIVER=/opt/ibm/db2/V10.5/lib64/libdb2.so.1;DATABASE=test;HOSTNAME=localhost;port=50000');
```

**Comment by RocketRooster** [comment] 2014-05-21 07:28
Hi, 

I decided to play around with unixodbc's isql to see what falls out. I am now getting the same issue as this guy: https://github.com/w1nk/node-odbc/issues/29

```
riaan@acs:~/manifest$ isql ACS -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> select * from acs.test
+------------+------------+----------+-------------+---------------------------+---------------+
| PK_TEST_ID | SOME_INT   | SOME_CHAR| SOME_VARCHAR| SOME_TIMESTAMP            | SOME_OTHER_INT|
+------------+------------+----------+-------------+---------------------------+---------------+
| 0          | 0          | #        | #           | #                         | #             |
+------------+------------+----------+-------------+---------------------------+---------------+
SQLRowCount returns -1
1 rows fetched
SQL> update acs.test set some_char = '!'
[01504][IBM][CLI Driver][DB2/LINUXX8664] SQL0513W  The SQL statement will modify an entire table or view.  SQLSTATE=01504

[ISQL]INFO: SQLExecute returned SQL_SUCCESS_WITH_INFO
SQLRowCount returns -4294967295
SQL> select * from acs.test
+------------+------------+----------+-------------+---------------------------+---------------+
| PK_TEST_ID | SOME_INT   | SOME_CHAR| SOME_VARCHAR| SOME_TIMESTAMP            | SOME_OTHER_INT|
+------------+------------+----------+-------------+---------------------------+---------------+
| 0          | 0          | !        | !           | !                         | !             |
+------------+------------+----------+-------------+---------------------------+---------------+
SQLRowCount returns -1
1 rows fetched
```

SOME_VARCHAR, SOME_TIMESTAMP and SOME_OTHER_INT are all null.

The respondent in question mentioned that he used a SQLLEN=4 version of the DB2 library, and that switching solved his problem, but didn't go into any detail. It would seem as if there is some bug in my libdb2.so.1, or otherwise it isn't compiled correctly.

Clearly, this isn't an issue with node-odbc in the least, so I don't want to hold you up further. When I figure out the solution, I will however update this issue in case anybody else suffers the same.

Thanks once again!
Riaan

**Comment by RocketRooster** [comment] 2014-05-21 09:35
Durrrrrrrr.

It probably helps to RTFM from time to time. The correct lib to use is libdb2o.so, not libdb2.so or libdb2.so.1 (these two libs are the CLI drivers, the *o.so files are the ODBC ones)

:facepalm:

More info here:

http://publib.boulder.ibm.com/infocenter/db2luw/v9r5/index.jsp?topic=%2Fcom.ibm.db2.luw.apdv.cli.doc%2Fdoc%2Ft0006349.html

Funny, though, that the CLI and ODBC drivers are pretty much identical apart from this....

Anyway, please carry on gents!
Riaan

**Comment by wankdanker** [comment] 2014-05-22 18:15
Lol. Oh well; these things happen. Enjoy!

I'm going to close the issue now.

Dan

**Closed as completed by wankdanker** 2014-05-22 18:15 UTC
