### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by amcintyre99** [w1nk/node-odbc#47] opened 2013-07-08 21:56 UTC
I've had what I think is a new memory leak when using your 5.14 and db2 in the last few weeks:
with db2 10.1 x64 - no leak
with db2 10.5 x64 - about 12gig of leak during 6.5 hour day - all accumulating in db2sysc process

So I thought it was strictly a db2 issue (10.5 is a new release) and nothing to do with node or odbc. And I've stayed with 10.5 because the callback times are so much better and I'm not swapping because of plenty of memory and daily reboots. But I did go back and forth there for a few days and proved it was 10.5 related.

However, when I put in your 5.19 on 7/5, the leak got a little worse. And today, with 5.20, still the same as 5.19. So could it be node or odbc somehow?

I would like to try and narrow this down to see if it's db2, node, odbc or who knows what.

And there may not be a leak at all and this could be just db2 10.5 and some new fancy buffer pool management.

At the latest node 10.12 and ubuntu 12.04.2.

I can install valgrind or whatever you think is best to resolve this.

Thanks!!

**Comment by wankdanker** [comment] 2013-07-08 22:11
Interesting. I suspect that there may be some memory leakage in node-odbc, but probably not in the manner that you are using it. Which if memory services is basically: open the database, prepare, bind, execute. And then repeating prepare, bind, execute or just bind, execute. 

But if there were a leak, I would expected it to be within the nodejs process, not in the database process. 

I have seen some minor leaks when multiple connections are opened and then lots of different result sets are created and the v8 garbage collector doesn't release the connection or result objects. Still trying to figure that out. 

I'm curious if with node-odbc v0.5.20 if you disable the UNICODE flag in `binding.gyp` if the leak goes back to v0.5.14 levels with db2 10.5. Just wondering if the extra 'leaked' memory usage is due to 2 bytes per character (UCS-2 encoding when UNICODE is enabled) vs 1 byte per character (UTF-8 when UNICODE is not enabled).

**Comment by amcintyre99** [comment] 2013-07-08 22:25
Took out UNICODE and did npm rebuild odbc. Will run with it all day on Tue and will update you about 4pm ET.

And the 12+gig of leak from today is still sitting in db2sysc if you know of any way to display/dump/look at it. And none of the usual db2 tools like db2top show any leak at all. It's like the 12gig isn't there to them.

**Comment by amcintyre99** [comment] 2013-07-08 22:31
And yes, most of my node code (by volume) does an initial db.prepareSync in the morning, then recursively calls itself via setTimeout all day, only executing stmt.executeNonQuery for millions of inserts.

Another node does db.prepareSync in the morning followed by stmt.execute, result.fetchAllSync and result.closeSync all day.

And no leak with this code at db2 10.1. Just 10.5.

**Comment by wankdanker** [comment] 2013-07-08 22:32
Unfortunately db2 is really out of my realm of experience. I find it very odd that though that the db2 tools don't report that memory. So, yeah, I wonder if part of the ODBC interaction with the db2sysc process actually resides within that process and is leaking there. I have no idea, though, I just made that up. :)

**Comment by wankdanker** [comment] 2013-07-08 22:32
Oh, so you tested node-odbc v0.5.19 with db2 10.1?

**Comment by amcintyre99** [comment] 2013-07-08 22:36
No, last tested at 10.1 was 5.14. Been staying with 10.5 because it's so much faster (callback millsec times are shorter).

Not sure if this matters but all of my code calling odbc is running in child_process.fork children nodes. Lots of them. All at the same time for multi-core scaling.

**Comment by amcintyre99** [comment] 2013-07-09 01:31
In the prepareSync (once) followed by many executeNonQuery's that I'm running (just like your "test/bench-prepare-executeNonQuery.js"), there are no explicit bind calls. I understood that your code was doing an implicit bind.

But in looking at your odbc_statement.cpp (which i shouldn't cause i have no idea what i'm looking at) I don't see a bind in executeNonQuery so I'm confused as to how this is actually working since I am using parameter markers.

Signed, should never look at c++ code...

**Comment by wankdanker** [comment] 2013-07-09 01:35
Hahaha. I hear ya. Start by looking at lib/odbc.js. That is what is actually exposed as the api. It wraps around the C++ modules and does some magic.

**Comment by wankdanker** [comment] 2013-07-09 01:46
Specifically line 491.

**Comment by amcintyre99** [comment] 2013-07-09 20:27
Yep, leak went back to normal (2gig less of a leak with UNICODE off). And by leak, it's still all in the db2sysc process.

So this makes me think that the normal leak is related to odbc as well, which is why I started this thread. But again, it's only related to db2 10.5 and odbc, not 10.1 and odbc. Weird...

On other platforms, there is a concept of a "stand alone dump" to dump the entire virtual memory. Then there are tools to process that dump. Right now there is about 12gig of leaked storage just sitting in virtual, which might be helpful if there was a way to display it...

**Comment by wankdanker** [comment] 2013-07-09 20:32
Could you run `ps u -C db2sysc` and paste it here?

**Comment by amcintyre99** [comment] 2013-07-09 20:53
$ ps u -C db2sysc
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
db2inst1  1502 47.1 43.0 15119012 10626320 ?   Sl   05:03 333:13 db2sysc 0

**Comment by amcintyre99** [comment] 2013-07-09 20:55
can't remember how to monospace something so here's gist
https://gist.github.com/amcintyre99/5961215

**Comment by amcintyre99** [comment] 2013-07-09 21:07
could this be unixodbc related? some difference between db2 10.1 and 10.5 that it's not handling?

**Comment by wankdanker** [comment] 2013-07-09 21:35
I'm not really sure. I'm not sure what unixodbc would leak into the db2 process. The db2 odbc driver is what really interacts with the db2 database processes, as far as I know.

The buffers and other memory that we allocate in node-odbc all reside within the node process. The only thing that I can think of that might leak into the database process would be unfreed handles to connections or statments. But since you are only creating one connection and statement per process, I would expect that not to be the case.

Will db2sysc continue to grow in size if you don't restart it? Or has it reached its peak and stay there with continued use? If it just stays there, the database process might just take as much physical ram as it can as it is needed and never release it. I think MSSQL does this too, but not sure.

**Comment by amcintyre99** [comment] 2013-07-09 22:04
It will continue to grow until Linux starts swapping. And remember, dropping UNICODE got me back 2gig.

One connection (at startup) and statement per long running process, for a lot of the work (multiple children nodes) all with setTimeout at 1 sec rerunning the function recursively.

But the biggest volume is multiple nodes, each with one connection (at startup) and one statement (not using setTimeout) but listening on multiple streams for http client "data" events. About 3mill inserts per 6.5 hour period.

The reason I'm looking at unixodbc is the number of times (and recent) I see the words leak and "out of memory" on this page: (and I'm back at some package level that comes with Ubuntu)
http://unixodbc.svn.sourceforge.net/viewvc/unixodbc/trunk/ChangeLog?view=log

Some of those mention the odbc W calls. Aren't they UNICODE?

**Comment by amcintyre99** [comment] 2013-07-09 22:09
And the box on the left is what I think I'm doing. And it shows the odbc driver manager in the middle all the time. I think.

**Comment by wankdanker** [comment] 2013-07-09 22:14
Yeah, W calls are Unicode. They should be not be used if the UNICODE flag is not enabled in `binding.gyp`. If they are used, then something weird is going on... But, yeah, maybe that is where that extra 2gigs was leaking from. But if that is the case then that means that unixodbc is leaking into the database process as you suggest. 

Of which box on the left do you speak?

**Comment by amcintyre99** [comment] 2013-07-09 22:18
Sorry, duh:
http://pic.dhe.ibm.com/infocenter/db2luw/v10r5/topic/com.ibm.db2.luw.apdv.cli.doc/doc/c0000670.html

**Comment by amcintyre99** [comment] 2013-07-09 22:25
Check out the 2.3.2pre fixes. You see any that look important? :-)

I've just emailed their support list (first time) to see if they will check out this thread.

**Comment by amcintyre99** [comment] 2013-07-09 22:25
Duh, did it again:
http://unixodbc.svn.sourceforge.net/viewvc/unixodbc/trunk/ChangeLog?revision=77&view=markup

**Comment by wankdanker** [comment] 2013-07-09 22:28
Nothing really screams out at me. But there are a couple memory related things. Not totally convinced. But, if you are feeling daring, you could compile it from source and see if it helps. ;-)

**Comment by praveend** [comment] 2013-07-10 17:30
@amcintyre99 to which support id have you sent out the mail. I will try following up with it to help narrow down to the area of problem.

**Comment by amcintyre99** [comment] 2013-07-10 18:10
I emailed unixodbc-support@mailman.unixodbc.org but haven't heard anything. I will also compile and try the latest as soon as I can...

**Comment by amcintyre99** [comment] 2013-07-10 18:28
And fyi, my db2cli.ini has Protocol = LOCAL so it uses IPC.

**Comment by wankdanker** [comment] 2013-07-10 18:36
Oh, I thought you emailed db2 support. :) 

Sorry, @praveend, I misunderstood what @amcintyre99 had done. Maybe someone from the db2 odbc team can take a look at this thread anyway. Thanks!

**Comment by praveend** [comment] 2013-07-12 12:25
@wankdanker sure...I will request one of the DB2 odbc members to look into this....

**Comment by amcintyre99** [comment] 2013-07-17 03:27
This may be one of those late night posts i regret in the morning but here goes...

In making a change I discovered that my "if (err)" code in the cb isn't catching any SQL errors... but it sure use to because I saw many during my early debugging.

In both of these sections in more than one program, the err object is null when there really is a SQL error:

``` bash
stmt.executeNonQuery([str,requ_ts,resp_ts],function(err,rows) {
  if(err) {

stmt.execute([],function(err,result) {
  if(err) {
```

But rows and result always have valid data returned to the cb when the SQL is ok.

Could this be related to this thread? or am I just making some js coding mistake (most likely).

**Comment by wankdanker** [comment] 2013-07-17 17:46
Never regrets for a late-night post. :)

I recall that issue before. I am having trouble reproducing it though. If you have any simplified code examples that can invoke a situation where you would expect an error to occur. Maybe you could start with this sample code:

``` js
var common = require("./common")
  , odbc = require("../")
  , db = new odbc.Database()
  , assert = require("assert")
  ;

db.open(common.connectionString, function(err){ 
  if (err) {
    console.error(err);
    process.exit(1);
  }

  issueQuery();
});

function issueQuery() {
  var count = 0
    , time = new Date().getTime();

  try {
    var stmt = db.prepareSync('select cast(? as datetime) as test');
  }
  catch (e) {
    console.log(e);
    return finish(1);
  }

  stmt.bind([], function (err) {
    if (err) {
      console.log(err);
      return finish(1);
    }

    stmt.execute(function (err, result) {
      if (err) {
        console.log(err);
        return finish(1);
      }

      console.log(result.fetchAllSync());

      finish(0);
    });
  });
}

function finish(exitCode) {
  db.close(function () {
    console.log("connection closed");

    process.exit(exitCode || 0);
  });
}
```

**Comment by amcintyre99** [comment] 2013-07-18 00:14
The code below shows the intermittent problem I'm hitting.

I've varied the setTimeout value from between 100 and 3000 and the problem shows, although more so at 100 than at 3000.

The problem shows in the console.log from cb like this:
0
0
101
0
0
101
101
101
0

The 101 row count is the correct number of inserts (it's a single call doing a multi row insert).

The 0 count with no error indication shows the problem!!

I've tried a function wrapper around stmt.executeNonQuery but no change.

Sorry this is just partial code...

``` bash
var db = new odbc.Database()

db.open("DRIVER={DB2};DATABASE=............",function(err) {

  if(err) {
    console.log(chld,err)
    db.close(function() {
    })
  } else {
    var stmt = db.prepareSync(sqlc)
    recursive(stmt)
  }

});

function recursive (stmt) {
  var requ_ts = microtime.now()

  request.post({url:url,oauth:oauth,timeout:10000},function(err,resp,str) {
    var resp_ts = microtime.now()

    if(err) {
      console.log(err)
    } else {
    stmt.executeNonQuery([str,requ_ts,resp_ts],cb);
    }

    setTimeout(function() {
      recursive(stmt)
      },100)
    })

};

function cb(err,rows) {
    if(err) {
      console.log(err)
      }
    console.log(rows)
};
```

**Comment by amcintyre99** [comment] 2013-07-18 00:50
If I purposely mess up the SQL (like by changing INSERT to NSERT), I get no error and rows shows -1.

**Comment by amcintyre99** [comment] 2013-07-18 01:24
And I did try your test code you worked up but couldn't get it to fail.

**Comment by amcintyre99** [comment] 2013-07-18 02:01
I just realized the endpoint I'm using is having issues so occasionally str has something I've never seen. So the INSERT would end up inserting 0 rows after the db2 xml parse found nada, which is not an error.

Duh, my bad on this error thing. My only excuse is that js makes my head hurt...

But I still have the leak.

**Comment by amcintyre99** [comment] 2013-07-18 02:22
Although I still don't understand why when the SQL has a syntax error on purpose, I don't get an error return.

Last post I swear. :-)

**Comment by wankdanker** [comment] 2013-07-18 02:28
Earlier today, I did find and fix the fact that prepareSync wasn't throwing when there was an error. There was just a nice TODO message saying, throw an error here. (https://github.com/wankdanker/node-odbc/commit/4d5e700d0042eb256477a6bf7b69cdb32134d88d) Although, now that I am reviewing that again, I see that the error message is wrong. :-\

So, good came of this regardless. :)

**Comment by amcintyre99** [comment] 2013-07-19 20:55
All day with 5.22, no issues.

Still have leak.

**Comment by amcintyre99** [comment] 2013-07-22 16:33
Just to verify, I don't need to close "rows" after executeNonQuery, right?

like I have to do with "result" after execute...

**Comment by wankdanker** [comment] 2013-07-22 16:41
Correct. `executeNonQuery` returns a Number object (http://izs.me/v8-docs/classv8_1_1Number.html). That object has no `close` method and it will be discarded by v8 as normal function arguments are discarded.

`execute` returns an ODBCResult object which has its own memory allocations that occur. It is required to call `close` on such a result object to make sure that allocated memory is released (within the node process).

**Comment by wankdanker** [comment] 2013-07-22 16:44
I should add that memory should be released if the `result` object is not explicitly `close`d. But that will only occur when the `result` object is garbage collected by v8. And there seems to be no guarantee of the timeliness of that. So, it is best to take care of it when you are done with it.

**Comment by amcintyre99** [comment] 2013-08-07 20:50
all day with node 10.15, odbc 5.25 on db2 10.5 - with dynodbc and no unicode

but still have leak - so i guess that rules out unixodbc

**Comment by wankdanker** [comment] 2013-10-08 19:03
Hey @amcintyre99 , I'm going to close this. Open a new ticket if you are experiencing memory leaks within the node process itself.

Thanks,

Dan

**Closed as completed by wankdanker** 2013-10-08 19:03 UTC
